services:
  movie-manager-db:
    image: postgres:17
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: movie-manager-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      start_period: 10s
      interval: 5s
      retries: 5
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  movie-manager-app:
    image: movie-manager-bot-app:latest
    env_file:
      - .env
    depends_on:
      movie-manager-db:
        condition: service_healthy
    environment:
      DB_HOST: movie-manager-db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    container_name: movie-manager-app
    volumes:
      - ./migrations:/migrations
      - ./.env:/app/.env