// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Stores movie information tracked by users
type Movie struct {
	ID        pgtype.UUID
	UserID    int64
	ApiID     int64
	Title     string
	Runtime   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

// Stores TV show information tracked by users
type TvShow struct {
	ID        pgtype.UUID
	UserID    int64
	ApiID     int64
	Name      string
	Seasons   int32
	Episodes  int32
	Runtime   int32
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

// Stores user information for authentication and preferences
type User struct {
	ID         pgtype.UUID
	TgID       int64
	FirstName  *string
	LastName   *string
	Username   *string
	Language   string
	TmdbApiKey *string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

// Stores shows and movies users want to watch
type Watchlist struct {
	ID        pgtype.UUID
	UserID    int64
	ShowApiID int64
	Type      string
	Title     string
	Image     *string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}
