// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package database

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, first_name, last_name, username, language, tmdb_api_key, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Language,
		&i.TmdbApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
