name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.CONTAINER_NAME }}:latest .

      - name: Save Docker Image to file
        run: |
          docker save ${{ secrets.CONTAINER_NAME }}:latest | gzip > ${{ secrets.CONTAINER_NAME }}.tar.gz

      - name: Install SSH Client
        run: |
          sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Copy Docker Image to Remote Server
        run: |
          scp ${{ secrets.CONTAINER_NAME }}.tar.gz $SSH_USER@$SSH_HOST:${{ secrets.LOCATION }}/images

        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Load Docker Image on Remote Server and Deploy
        run: |
          ssh $SSH_USER@$SSH_HOST "
          docker load -i ${{ secrets.LOCATION }}/images/${{ secrets.CONTAINER_NAME }}.tar.gz &&
          docker stop ${{ secrets.CONTAINER_NAME }} || true &&
          docker rm ${{ secrets.CONTAINER_NAME }} || true &&
          cd ${{ secrets.LOCATION }} && docker compose up -d"

        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
          LOCATION: ${{ secrets.LOCATION }}
